import { nanoid } from 'nanoid';
import dayjs from 'dayjs';

export const state = () => ({
	users: [
		{
			username: 'matijao',
			fname: 'Matija',
			lname: 'Osrečki',
			countryCode: 'HRV',
			birthday: dayjs('1999-12-10'),
			joined_on: dayjs('2021-01-16'),

			photo:
				'https://avatar.oxro.io/avatar.svg?name=matija+osrečki&caps=1',
			occupation: 'Student',
			bio: 'Different strokes for different folkes 🍭',
			coins: 400,
			isPremium: true,
			categories: [
				'8MNLJ4yg15YoRch0t3NAG',
				'0TN9zbVVaZOhWswtztYYn',
				'VQDonT7_pB4ACAW6DZsiL',
			], // mogli bi ih automatski postavljat na temelju njegovih najcescih todosa
			socials: [
				{ id: 'twitter', url: 'https://www.google.com/' },
				{ id: 'linkedin', url: 'https://www.google.com/' },
				{ id: 'github', url: 'https://www.google.com/' },
				{ id: 'telegram', url: 'https://www.google.com/' },
				{ id: 'discord', url: 'https://www.google.com/' },
				{ id: 'dribbble', url: 'https://www.google.com/' },
				{ id: 'stack-overflow', url: 'https://www.google.com/' },
				{ id: 'medium', url: 'https://www.google.com/' },
				{ id: 'bitcoin', url: 'https://www.google.com/' },
			],
			todos: [
				{
					id: nanoid(),
					name: 'Procitati knjigu',
					desc: '', // optional
					categories: [
						{ id: nanoid(), name: 'reading', color: 'red' },
						{ id: nanoid(), name: 'mindfulness', color: 'amber' },
					],
					timestamp: 1618916803496,
					done: false,
					approved: false,
					isDaily: false,
					favorite: false,
					important: false,
					partner: 'patrik_harmonika',
				},
				{
					id: nanoid(),
					name: 'odvoziti bicikl',
					desc: '', // optional
					categories: [
						{ id: nanoid(), name: 'health', color: 'lightBlue' },
						{ id: nanoid(), name: 'fitness', color: 'violet' },
						{ id: nanoid(), name: 'nature', color: 'emerald' },
					],
					timestamp: 1618916803496,
					done: true,
					approved: false,
					isDaily: false,
					favorite: false,
					important: false,
					partner: 'marian7',
				},
				{
					id: nanoid(),
					name: 'random task',
					desc: '', // optional
					categories: [],
					timestamp: 1618916803496,
					done: true,
					approved: false,
					isDaily: false,
					favorite: false,
					important: false,
					partner: null,
				},
				{
					id: nanoid(),
					name: 'napraviti pripremu iz Bazi Podataka',
					desc: '', // optional
					categories: [
						{ id: nanoid(), name: 'study', color: 'teal' },
						{ id: nanoid(), name: 'school', color: 'indigo' },
						{ id: nanoid(), name: 'coding', color: 'blue' },
					],
					timestamp: 1618916803496,
					done: false,
					approved: false,
					isDaily: false,
					favorite: false,
					important: false,
					partner: 'tomoKotar14',
				},
				{
					id: nanoid(),
					name: 'pogledati utakmicu',
					desc: '', // optional
					categories: [{ id: nanoid(), name: 'fun', color: 'pink' }],
					timestamp: 1618916803496,
					done: false,
					approved: false,
					isDaily: false,
					favorite: false,
					important: false,
					partner: null,
				},
				{
					id: nanoid(),
					name: 'live life',
					desc: '', // optional
					categories: [],
					timestamp: 1618916803496,
					done: false,
					approved: false,
					isDaily: false,
					favorite: false,
					important: false,
					partner: null,
				},
			],
			notifications: [
				'Marian forgot to share his screen',
				'Tomo liked your streak',
				'You were voted best programmer on the platform 3rd month in a row',
				'Marian endorsed your Vue skills',
				'Koraljka liked your goals list',
				'Stan Svenovljević joined you in your monthly challenge',
				'Stan Svenovljević commented on your post',
			],
		},
		{
			username: 'marian7',
			fname: 'Marian',
			lname: 'Babić',
			countryCode: 'COL',
			birthday: dayjs('2000-11-01'),
			joined_on: dayjs('2021-11-04'),

			photo: 'https://avatar.oxro.io/avatar.svg?name=marian+babić&caps=1',
			occupation: 'Student',
			bio: 'Ad sed sunt qui sunt vel.',
			coins: 234,
			isPremium: true,
			categories: [
				'0iUqkyVh0IliBfXtyOj7r',
				'8MNLJ4yg15YoRch0t3NAG',
				'0TN9zbVVaZOhWswtztYYn',
			],
			socials: [
				{ id: 'facebook', url: 'https://www.google.com/' },
				{ id: 'messenger', url: 'https://www.google.com/' },
				{ id: 'github', url: 'https://www.google.com/' },
				{ id: 'discord', url: 'https://www.google.com/' },
				{ id: 'whatsapp', url: 'https://www.google.com/' },
				{ id: 'stack-overflow', url: 'https://www.google.com/' },
				{ id: 'default', url: 'https://www.google.com/' },
			],
			todos: [],
		},
		{
			username: 'patrik_harmonika',
			fname: 'Patrik',
			lname: 'Slovic',
			countryCode: 'HR',
			birthday: dayjs('1994-05-20'),
			joined_on: dayjs('2020-09-27'),

			photo:
				'https://avatar.oxro.io/avatar.svg?name=Patrik+Slovic&caps=1',
			occupation: 'Musician',
			bio: 'Amet fugiat sequi.',
			coins: 643,
			isPremium: false,
			categories: [
				'jcE5bvcPrBYb2bstsEWgE',
				'xUMFQYg3iBJbptNBUqsCK',
				'Bzw_jJ7m-I6vuN4HaFsDv',
			],
			socials: [
				{ id: 'facebook', url: 'https://www.google.com/' },
				{ id: 'linkedin', url: 'https://www.google.com/' },
				{ id: 'unsplash', url: 'https://www.google.com/' },
				{ id: 'quora', url: 'https://www.google.com/' },
				{ id: 'patreon', url: 'https://www.google.com/' },
				{ id: 'pinterest', url: 'https://www.google.com/' },
				{ id: 'youtube', url: 'https://www.google.com/' },
			],
			todos: [],
		},
		{
			username: 'tomoKotar14',
			fname: 'Tomislav',
			lname: 'Mikšik',
			countryCode: 'BEL',
			birthday: dayjs('1995-07-21'),
			joined_on: dayjs('2021-03-01'),

			photo:
				'https://avatar.oxro.io/avatar.svg?name=Tomislav+Mikšik&caps=1',
			occupation: 'Influencer',
			bio: 'Explicabo doloribus aspernatur in.',
			coins: 110,
			isPremium: false,
			categories: ['4OgWmONbRqhKYtDJTjd0I', '0TN9zbVVaZOhWswtztYYn'],
			socials: [
				{ id: 'reddit', url: 'https://www.google.com/' },
				{ id: 'twitter', url: 'https://www.google.com/' },
				{ id: 'facebook', url: 'https://www.google.com/' },
				{ id: 'discord', url: 'https://www.google.com/' },
				{ id: 'youtube', url: 'https://www.google.com/' },
				{ id: 'whatsapp', url: 'https://www.google.com/' },
				{ id: 'bitcoin', url: 'https://www.google.com/' },
			],
			todos: [],
		},
		{
			username: 'lovedoctor',
			fname: 'Warren',
			lname: 'Lowe',
			countryCode: 'GAB',
			birthday: dayjs('1978-11-04'),
			joined_on: dayjs('2021-02-14'),
			photo: 'https://randomuser.me/api/portraits/men/83.jpg',
			occupation: 'Doctor',
			bio: 'Nulla error omnis debitis libero id repellendus.',
			coins: 643,
			isPremium: false,
			categories: ['kmTtKxOMeKfuNoU_kG-yp'],
			socials: [
				{ id: 'facebook', url: 'https://www.google.com/' },
				{ id: 'patreon', url: 'https://www.google.com/' },
				{ id: 'unsplash', url: 'https://www.google.com/' },
				{ id: 'quora', url: 'https://www.google.com/' },
			],
			todos: [],
		},
		{
			username: 'wood42',
			fname: 'Joseph',
			lname: 'Woodward',
			countryCode: 'USA',
			birthday: dayjs('1991-07-07'),
			joined_on: dayjs('2020-12-11'),

			photo: 'https://randomuser.me/api/portraits/men/23.jpg',
			occupation: 'Coach',
			bio: '',
			coins: 32,
			isPremium: false,
			categories: ['BR2eOYR1Y6u_Yp_H58xD1', '8MNLJ4yg15YoRch0t3NAG'],
			socials: [
				{ id: 'twitter', url: 'https://www.google.com/' },
				{ id: 'stack-overflow', url: 'https://www.google.com/' },
				{ id: 'medium', url: 'https://www.google.com/' },
				{ id: 'youtube', url: 'https://www.google.com/' },
			],
			todos: [],
		},
		{
			username: 'suzzy',
			fname: 'Suzanne',
			lname: 'Hunter',
			countryCode: 'TWN',
			birthday: dayjs('1988-01-09'),
			joined_on: dayjs('2021-04-10'),
			photo: 'https://randomuser.me/api/portraits/women/35.jpg',
			occupation: 'Fireman',
			bio: 'Velit ut ut aut ut magni esse.',
			coins: 643,
			isPremium: false,
			categories: ['VquU1OBaiUo02JuSuZRO8', 'uUCM7KHa7XlSzqpqX7iY3'],
			socials: [
				{ id: 'pinterest', url: 'https://www.google.com/' },
				{ id: 'messenger', url: 'https://www.google.com/' },
				{ id: 'whatsapp', url: 'https://www.google.com/' },
				{ id: 'tumblr', url: 'https://www.google.com/' },
				{ id: 'youtube', url: 'https://www.google.com/' },
			],
			todos: [],
		},
	],
	users2: [
		{
			username: 'marian7',
			fname: 'Barian',
			lname: 'Mamić',
			age: 24,
			photo: 'https://avatar.oxro.io/avatar.svg?name=m+b&caps=1',
			bio: 'Skoro sam zaspo 7 puta. U ovih pol@sata',
			country: 'Croatia', // ili country code; dohvatit cu zastavu prek apija
			joined_on: 'January, 2021', // timestamp kad je kreirao account
			coins: 201,
			occupation: 'Student',
			// categories: [{ id: '', name: '' }],
			// badges: [{ id: '', name: '', timestamp: null }],
			rank: null,
			isPrivate: false,
			isPremium: false,
			todos: [
				{
					id: nanoid(),
					name: 'Procitati knjigu',
					desc: '', // optional
					categories: [
						{ id: nanoid(), name: 'reading', color: 'red' },
						{ id: nanoid(), name: 'mindfulness', color: 'amber' },
					], // ovo ce bit posebna tablica, referencamo idjem,
					timestamp: 1618916803496,
					done: false,
					approved: false,
					isDaily: false,
					favorite: false,
					important: false,
					partner: 'patrik_harmonika',
				},
				{
					id: nanoid(),
					name: 'odvoziti bicikl',
					desc: '', // optional
					categories: [
						{ id: nanoid(), name: 'health', color: 'lightBlue' },
						{ id: nanoid(), name: 'fitness', color: 'violet' },
						{ id: nanoid(), name: 'nature', color: 'emerald' },
					],
					timestamp: 1618916803496,
					done: true,
					approved: false,
					isDaily: false,
					favorite: false,
					important: false,
					partner: null,
				},
				{
					id: nanoid(),
					name: 'random task',
					desc: '', // optional
					categories: [], // ovo ce bit posebna tablica, referencamo idjem,
					timestamp: 1618916803496,
					done: false,
					approved: false,
					isDaily: false,
					favorite: false,
					important: false,
					partner: null,
				},
				{
					id: nanoid(),
					name: 'napraviti pripremu iz Bazi Podataka',
					desc: '', // optional
					categories: [
						{ id: nanoid(), name: 'study', color: 'teal' },
						{ id: nanoid(), name: 'school', color: 'indigo' },
						{ id: nanoid(), name: 'coding', color: 'blue' },
					],
					timestamp: 1618916803496,
					done: false,
					approved: false,
					isDaily: false,
					favorite: false,
					important: false,
					partner: 'tomoKotar14',
				},
				{
					id: nanoid(),
					name: 'pogledati utakmicu',
					desc: '', // optional
					categories: [{ id: nanoid(), name: 'fun', color: 'pink' }],
					timestamp: 1618916803496,
					done: false,
					approved: false,
					isDaily: false,
					favorite: false,
					important: false,
					partner: null,
				},
				{
					id: nanoid(),
					name: 'live life',
					desc: '', // optional
					categories: [], // ovo ce bit posebna tablica, referencamo idjem,
					timestamp: 1618916803496,
					done: false,
					approved: false,
					isDaily: false,
					favorite: false,
					important: false,
					partner: null,
				},
			],
			notifications: [
				'Matija gave you recognition',
				'Zoki commented on your post',
				'Patrik beat your streak',
				'Lorena loves you and takes care of you',
				'Matija endorsed your exceptional Vue skills',
			],
			socials: [
				'instagram',
				'linkedin',
				'github',
				'discord',
				'stack-overflow',
				'whatsapp',
				'messenger',
			],
		},
		{
			username: 'matijao',
			fname: 'Matija',
			lname: 'Osrečki',
			age: 17,
			// photo:
			// 	'https://pbs.twimg.com/profile_images/669103856106668033/UF3cgUk4_400x400.jpg',
			photo: 'https://avatar.oxro.io/avatar.svg?name=Matija+Osrecki',
			bio: 'Different strokes for different folkes 🍭',
			country: 'Croatia',
			joined_on: 'March, 2021',
			coins: 211,
			occupation: 'Web Dev',
			// categories: [{ id: '', name: '' }],
			// badges: [{ id: '', name: '', timestamp: null }],
			rank: null,
			isPrivate: false,
			isPremium: true,
			todos: [
				{
					id: nanoid(),
					name: 'Procitati knjigu',
					desc: '', // optional
					categories: [
						{ id: nanoid(), name: 'reading', color: 'red' },
						{ id: nanoid(), name: 'mindfulness', color: 'amber' },
					], // ovo ce bit posebna tablica, referencamo idjem,
					timestamp: 1618916803496,
					done: false,
					approved: false,
					isDaily: false,
					favorite: false,
					important: false,
					partner: 'patrik_harmonika',
				},
				{
					id: nanoid(),
					name: 'odvoziti bicikl',
					desc: '', // optional
					categories: [
						{ id: nanoid(), name: 'health', color: 'lightBlue' },
						{ id: nanoid(), name: 'fitness', color: 'violet' },
						{ id: nanoid(), name: 'nature', color: 'emerald' },
					],
					timestamp: 1618916803496,
					done: true,
					approved: false,
					isDaily: false,
					favorite: false,
					important: false,
					partner: 'marian7',
				},
				{
					id: nanoid(),
					name: 'random task',
					desc: '', // optional
					categories: [], // ovo ce bit posebna tablica, referencamo idjem,
					timestamp: 1618916803496,
					done: true,
					approved: false,
					isDaily: false,
					favorite: false,
					important: false,
					partner: null,
				},
				{
					id: nanoid(),
					name: 'napraviti pripremu iz Bazi Podataka',
					desc: '', // optional
					categories: [
						{ id: nanoid(), name: 'study', color: 'teal' },
						{ id: nanoid(), name: 'school', color: 'indigo' },
						{ id: nanoid(), name: 'coding', color: 'blue' },
					],
					timestamp: 1618916803496,
					done: false,
					approved: false,
					isDaily: false,
					favorite: false,
					important: false,
					partner: 'tomoKotar14',
				},
				{
					id: nanoid(),
					name: 'pogledati utakmicu',
					desc: '', // optional
					categories: [{ id: nanoid(), name: 'fun', color: 'pink' }],
					timestamp: 1618916803496,
					done: false,
					approved: false,
					isDaily: false,
					favorite: false,
					important: false,
					partner: null,
				},
				{
					id: nanoid(),
					name: 'live life',
					desc: '', // optional
					categories: [],
					timestamp: 1618916803496,
					done: false,
					approved: false,
					isDaily: false,
					favorite: false,
					important: false,
					partner: null,
				},
			],
			notifications: [
				'Marian forgot to share his screen',
				'Tomo liked your streak',
				'You were voted best programmer on the platform 3rd month in a row',
				'Marian endorsed your Vue skills',
				'Koraljka liked your goals list',
				'Stan Svenovljević joined you in your monthly challenge',
				'Stan Svenovljević commented on your post',
			],
			socials: [
				'github',
				'linkedin',
				'discord',
				'telegram',
				'reddit',
				'codepen',
				'dribbble',
				'behance',
				'stack-overflow',
				'medium',
				'bitcoin',
			],
		},
		{
			username: 'patrik_harmonika',
			fname: 'Patrik',
			lname: 'Slovic',
			age: 55,
			photo:
				'https://pbs.twimg.com/profile_images/988775660163252226/XpgonN0X.jpg',
			bio: 'Mi culo está en fuego',
			country: 'Spain',
			joined_on: 'January, 2021',
			coins: 453,
			occupation: 'Musician',
			// categories: [{ id: '', name: '' }],
			// badges: [{ id: '', name: '', timestamp: null }],
			rank: null,
			isPrivate: false,
			isPremium: false,
			notifications: ['Zoki sent you a partner request'],
			socials: [
				'facebook',
				'linkedin',
				'unsplash',
				'quora',
				'patreon',
				'pinterest',
				'youtube',
			],
		},
		{
			username: 'tomoKotar14',
			fname: 'Tomislav',
			lname: 'Mikšik',
			age: 34,
			photo:
				'https://pbs.twimg.com/profile_images/712382030064062465/HoG1N4E0_400x400.jpg',
			bio: 'Bio i ošo',
			country: 'Nigeria',
			joined_on: 'October, 2020',
			coins: 45,
			occupation: 'Farm owner',
			// categories: [{ id: '', name: '' }],
			// badges: [{ id: '', name: '', timestamp: null }],
			rank: null,
			isPrivate: false,
			isPremium: false,
			notifications: [],
			socials: [
				'reddit',
				'twitter',
				'facebook',
				'discord',
				'youtube',
				'whatsapp',
				'bitcoin',
			],
		},
		{
			username: 'svenich',
			fname: 'Stan',
			lname: 'Svenovljević',
			age: 11,
			photo:
				'https://www.dalia-partyshop.hr/sites/default/files/styles/large/public/2018-04/Vatrogasac%20Vjeko_0.jpg',
			bio: '🐀🐀🐀🐀🐀',
			country: 'Kosovo',
			joined_on: 'April, 2021',
			coins: 6,
			occupation: 'Unemployed',
			// categories: [{ id: '', name: '' }],
			// badges: [{ id: '', name: '', timestamp: null }],
			rank: null,
			isPrivate: false,
			isPremium: false,
			notifications: ['Matija beat your bench press national record'],
			socials: ['youtube', 'whatsapp', 'tumblr'],
		},
		{
			username: 'markoc',
			fname: 'Marko',
			lname: 'Kubanić',
			age: 42,
			photo:
				'https://cachedimages.podchaser.com/256x256/aHR0cHM6Ly9jcmVhdG9yLWltYWdlcy5wb2RjaGFzZXIuY29tLzNmMWY5MThiNzc2NTQwNWI5NzdhMzQ5MzFjYzgwOGE0LmpwZWc%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D',
			bio:
				"I still work hard to know my business. I'm continuously looking for ways to improve all my companies, and I'm always selling. Always.",
			country: 'USA',
			joined_on: 'April, 2021',
			coins: 695,
			occupation: 'Investor',
			// categories: [{ id: '', name: '' }],
			// badges: [{ id: '', name: '', timestamp: null }],
			rank: null,
			isPrivate: false,
			isPremium: true,
			notifications: [
				'Marian liked your daily streak',
				'Matija responded to your latest todo',
				'Stan Svenovljević sent you a partner request and we automatically rejected it for you',
			],
			socials: [
				'twitter',
				'youtube',
				'reddit',
				'discord',
				'telegram',
				'personal',
				'bitcoin',
			],
		},
		{
			username: 'koralj11',
			fname: 'Koraljka Dunja',
			lname: 'Vinfrić-Jagodžić',
			age: 50,
			photo:
				'https://thumbor.forbes.com/thumbor/fit-in/416x416/filters%3Aformat%28jpg%29/https%3A%2F%2Fspecials-images.forbesimg.com%2Fimageserve%2F5ed6730fc6ade40006ffd657%2F0x0.jpg%3Fbackground%3D000000%26cropX1%3D0%26cropX2%3D1080%26cropY1%3D0%26cropY2%3D1080',
			bio:
				'Duct tape is like the force. It has a light side, and it holds the world together.',
			country: 'Montenegro',
			joined_on: 'January, 2021',
			coins: 156,
			occupation: 'Cashier',
			// categories: [{ id: '', name: '' }],
			// badges: [{ id: '', name: '', timestamp: null }],
			rank: null,
			isPrivate: false,
			isPremium: true,
			notifications: [
				'You forgot te respond to your partner and we dedicted 10 coins from you',
				'You havent logged in for a while',
			],
			socials: [
				'twitter',
				'facebook',
				'youtube',
				'quora',
				'slack',
				'personal',
			],
		},
	],
});

export const getters = {
	users(state) {
		return state.users || [];
	},
	getUserById: (state, getters) => (username) => {
		return getters.users.find((user) => user.username === username);
	},
	getUserTodos: (state, getters) => (username) => {
		return getters.users.find((user) => user.username === username)?.todos;
	},
};

// export const mutations = {
// 	updateValue(state, payload) {
// 		state.value = payload;
// 	},
// };

export const actions = {};
